#ifndef LEDHARDWARE_H_INCLUDED
#define LEDHARDWARE_H_INCLUDED

#ifdef MAIN_BUILT
  #define LEDROT_PORT   PORTA
  #define LEDROT_PIN    PIN2_bm
  #define LEDGRUEN_PORT PORTA
  #define LEDGRUEN_PIN  PIN4_bm
  #define LEDGELB_PORT  PORTA
  #define LEDGELB_PIN   PIN3_bm
#endif // MAIN_BUILT

#ifdef PLUG_BUILT
  /* LED auf Basisplatine */
  #define LEDROT_PORT   PORTA
  #define LEDROT_PIN    PIN2_bm
  #define LEDGRUEN_PORT PORTA
  #define LEDGRUEN_PIN  PIN3_bm
  #define LEDGELB_PORT  PORTA
  #define LEDGELB_PIN   PIN4_bm
#endif // PLUG_BUILT




#define LEDROTSETUP     LEDROT_PORT.DIRSET=LEDROT_PIN
#define LEDROT_ON       LEDROT_PORT.OUTCLR=LEDROT_PIN
#define LEDROT_OFF      LEDROT_PORT.OUTSET=LEDROT_PIN
#define LEDROT_TOGGLE   LEDROT_PORT.OUTTGL=LEDROT_PIN

#define LEDGRUENSETUP     LEDGRUEN_PORT.DIRSET=LEDGRUEN_PIN
#define LEDGRUEN_ON       LEDGRUEN_PORT.OUTCLR=LEDGRUEN_PIN
#define LEDGRUEN_OFF      LEDGRUEN_PORT.OUTSET=LEDGRUEN_PIN
#define LEDGRUEN_TOGGLE   LEDGRUEN_PORT.OUTTGL=LEDGRUEN_PIN

#define LEDGELBSETUP    LEDGELB_PORT.DIRSET=LEDGELB_PIN
#define LEDGELB_ON      LEDGELB_PORT.OUTCLR=LEDGELB_PIN
#define LEDGELB_OFF     LEDGELB_PORT.OUTSET=LEDGELB_PIN
#define LEDGELB_TOGGLE  LEDGELB_PORT.OUTTGL=LEDGELB_PIN


#endif // LEDHARDWARE_H_INCLUDED
